name: OutfitPvP
main: Outfit.PvP.Main.Main
version: 2.1
author: Danih , Rafael Auler
description: Plugin de kitpvp OutfitPvP
commands:
  admin:
  autosoup:
  bc:
  build:
  cage:
  cc:
  reloadcfg:
  chat:
  darcoins:
  speed1v1:
  1v1set:
  loc1set:
  1v1:
  loc2set:
  finalizar:
  voidset:
  warps:
  fly:
  gm:
  ssset:
  doar:
  mdrset:
  mdr:
  mlg:
  mlgset:
  void:
  txset:
  loja:
   aliases: [vip]
  textura:
  kbset:
  tpevento:
  knockback:
  fisherman:
  fishset:
  potionset:
  potion:
  head:
  lag:
  arenaset:
  arena:
  ss:
  iniciar:
  regras:
  status:
  inv:
  kit:
  liga:
   aliases: [rank]
  youtuber:
   aliases: [yt]  
  testmacro:
  ping:
  pvp:
  score:
  marca:
  setarena:
  setgroup:
  clan:
  setvip:
  skit:
  speedsumo:
  sumoset:
  s1set:
  s2set:
  sumo:
  sc:
  sortearkit:
  sortearvip:
  tag:
  tpall:
  tp:
  tphere:
   aliases: [here]
  vis:
  limpartela:
  recraft:
  tell:
   aliases: [r]
  aplicar:
  ajuda:
   aliases: [discord]
  report:
  fps:
  crash:
  sudo:
  consolesudo:
  morrer:
  challenge:
  evento:
  parkour:
  rdmset:
  fpsset:
  challengeset:
  eventoset:
  parkourset:
  mainset:
  spawnset:
  main:
  spawn:
   aliases: [lobby]
  lojakits:
  rdm:
  lojaextras: